let e;
let b;

function updateDisplayPageLoadSetup() {
  e = [document.getElementById("e0"), document.getElementById("e1"), document.getElementById("e2"), document.getElementById("e3"), document.getElementById("e4"), document.getElementById("e5"), document.getElementById("e6"), document.getElementById("e7"), document.getElementById("e8"), document.getElementById("e9"), document.getElementById("e10"), document.getElementById("e11"), document.getElementById("e12"), document.getElementById("e13"), document.getElementById("e14"), document.getElementById("e15"), document.getElementById("e16"), document.getElementById("e17"), document.getElementById("e18"), document.getElementById("e19"), document.getElementById("e20"), document.getElementById("e21"), document.getElementById("e22"), document.getElementById("e23"), document.getElementById("e24"), document.getElementById("e25"), document.getElementById("e26"), document.getElementById("e27"), document.getElementById("e28"), document.getElementById("e29"), document.getElementById("e30"), document.getElementById("e31"), document.getElementById("e32"), document.getElementById("e33"), document.getElementById("e34"), document.getElementById("e35"), document.getElementById("e36"), document.getElementById("e37"), document.getElementById("e38"), document.getElementById("e39"), document.getElementById("e40"), document.getElementById("e41"), document.getElementById("e42"), document.getElementById("e43")];
  b = [document.getElementById("b0"), document.getElementById("b1"), document.getElementById("b2"), document.getElementById("b3"), document.getElementById("b4"), document.getElementById("b5"), document.getElementById("b6"), document.getElementById("b7"), document.getElementById("b8"), document.getElementById("b9"), document.getElementById("b10"), document.getElementById("b11"), document.getElementById("b12"), document.getElementById("b13"), document.getElementById("b14"), document.getElementById("b15"), document.getElementById("b16"), document.getElementById("b17"), document.getElementById("b18"), document.getElementById("b19"), document.getElementById("b20"), document.getElementById("b21"), document.getElementById("b22"), document.getElementById("b23"), document.getElementById("b24"), document.getElementById("b25"), document.getElementById("b26"), document.getElementById("b27"), document.getElementById("b28"), document.getElementById("b29"), document.getElementById("b30"), document.getElementById("b31"), document.getElementById("b32"), document.getElementById("b33"), document.getElementById("b34"), document.getElementById("b35"), document.getElementById("b36"), document.getElementById("b37"), document.getElementById("b38"), document.getElementById("b39"), document.getElementById("b40"), document.getElementById("b41"), document.getElementById("b42"), document.getElementById("b43"), document.getElementById("b44"), document.getElementById("b45"), document.getElementById("b46"), document.getElementById("b47"), document.getElementById("b48"), document.getElementById("b49"), document.getElementById("b50"), document.getElementById("b51"), document.getElementById("b52"), document.getElementById("b53"), document.getElementById("b54"), document.getElementById("b55"), document.getElementById("b56"), document.getElementById("b57"), document.getElementById("b58"), document.getElementById("b59"), document.getElementById("b60"), document.getElementById("b61"), document.getElementById("b62"), document.getElementById("b63"), document.getElementById("b64"), document.getElementById("b65"), document.getElementById("b66"), document.getElementById("b67"), document.getElementById("b68"), document.getElementById("b69"), document.getElementById("b70"), document.getElementById("b71"), document.getElementById("b72"), document.getElementById("b73"), document.getElementById("b74"), document.getElementById("b75"), document.getElementById("b76"), document.getElementById("b77")];
}

function updateDisplaySaveLoadSetup() {
  b[0].value = Options.notation();
  b[0].onchange = function() {Options.setNotation(this.value)};
  b[1].value = Options.buildAmount();
  b[1].onchange = function() {Options.setBuildAmount(+this.value)};
}

function updateDisplay() {
  e[0].textContent = player.options.offlineProgress ? "On" : "Off";
  e[1].textContent = formatInt(Stuff.amount());
  e[2].textContent = formatInt(Equip.amount('tshirt', ShrinkLevel.level()));
  e[3].textContent = Equip.spaceDisplay('tshirt', ShrinkLevel.level());
  e[4].textContent = formatInt(Equip.buildAmount('tshirt', ShrinkLevel.level()));
  e[5].textContent = pluralize(Equip.buildAmount('tshirt', ShrinkLevel.level()), '', 's');
  e[6].textContent = formatInt(Equip.costForAllDisplay('tshirt', ShrinkLevel.level()));
  e[7].textContent = formatInt(Equip.amount('tent', ShrinkLevel.level()));
  e[8].textContent = Equip.spaceDisplay('tent', ShrinkLevel.level());
  e[9].textContent = formatInt(Equip.buildAmount('tent', ShrinkLevel.level()));
  e[10].textContent = pluralize(Equip.buildAmount('tent', ShrinkLevel.level()), '', 's');
  e[11].textContent = formatInt(Equip.costForAllDisplay('tent', ShrinkLevel.level()));
  e[12].textContent = formatInt(Equip.amount('dart', ShrinkLevel.level()));
  e[13].textContent = Equip.spaceDisplay('dart', ShrinkLevel.level());
  e[14].textContent = formatInt(Equip.buildAmount('dart', ShrinkLevel.level()));
  e[15].textContent = pluralize(Equip.buildAmount('dart', ShrinkLevel.level()), '', 's');
  e[16].textContent = formatInt(Equip.costForAllDisplay('dart', ShrinkLevel.level()));
  e[17].textContent = formatInt(Equip.amount('trap', ShrinkLevel.level()));
  e[18].textContent = Equip.spaceDisplay('trap', ShrinkLevel.level());
  e[19].textContent = formatInt(Equip.buildAmount('trap', ShrinkLevel.level()));
  e[20].textContent = pluralize(Equip.buildAmount('trap', ShrinkLevel.level()), '', 's');
  e[21].textContent = formatInt(Equip.costForAllDisplay('trap', ShrinkLevel.level()));
  e[22].textContent = Traps.isTrapping() ? "On" : "Off";
  e[23].textContent = formatInt(Trims.amount());
  e[24].textContent = format(Trims.gatheringProduction());
  e[25].textContent = format(Trims.breedingProduction());
  e[26].textContent = formatInt(Zone.zone());
  e[27].textContent = formatInt(Zone.cell());
  e[28].textContent = formatInt(Zone.fightingGroupSize());
  e[29].textContent = pluralize(Zone.fightingGroupSize(), '', 's');
  e[30].textContent = Zone.isAutoFightOn() ? "On" : "Off";
  e[31].textContent = formatInt(Zone.trimCount());
  e[32].textContent = pluralize(Zone.trimCount(), '', 's');
  e[33].textContent = formatInt(Zone.trimAttack());
  e[34].textContent = formatInt(Zone.trimHealth());
  e[35].textContent = formatInt(Zone.trimMaxHealth());
  e[36].textContent = Zone.enemyName();
  e[37].textContent = formatInt(Zone.enemyAttack());
  e[38].textContent = formatInt(Zone.enemyHealth());
  e[39].textContent = formatInt(Zone.enemyMaxHealth());
  e[40].textContent = Zone.book(4);
  e[41].textContent = Zone.book(3);
  e[42].textContent = Zone.book(2);
  e[43].textContent = Zone.book(1);
  
  
  b[2].value = Equip.fractionSpaceOfType('trap');
  b[3].value = Equip.fractionSpaceOfType('armor');
  b[4].value = Equip.fractionSpaceOfType('housing');
  b[5].value = Equip.fractionSpaceOfType('weapon');
  b[6].className = Equip.buildAmount('tshirt', ShrinkLevel.level()) === 0 ? 'disabled' : '';
  b[7].className = Equip.buildAmount('tent', ShrinkLevel.level()) === 0 ? 'disabled' : '';
  b[8].className = Equip.buildAmount('dart', ShrinkLevel.level()) === 0 ? 'disabled' : '';
  b[9].className = Equip.buildAmount('trap', ShrinkLevel.level()) === 0 ? 'disabled' : '';
  b[10].value = Trims.fraction();
  b[11].className = Zone.canSendGroupToFight() ? '' : 'disabled';
  b[12].value = Zone.trimHealthFraction();
  b[13].value = Zone.enemyHealthFraction();
  b[14].style.backgroundColor = Zone.getCellColor(8, 1);
  b[15].style.backgroundColor = Zone.getCellColor(8, 2);
  b[16].style.backgroundColor = Zone.getCellColor(8, 3);
  b[17].style.backgroundColor = Zone.getCellColor(8, 4);
  b[18].style.backgroundColor = Zone.getCellColor(8, 5);
  b[19].style.backgroundColor = Zone.getCellColor(8, 6);
  b[20].style.backgroundColor = Zone.getCellColor(8, 7);
  b[21].style.backgroundColor = Zone.getCellColor(8, 8);
  b[22].style.backgroundColor = Zone.getCellColor(7, 1);
  b[23].style.backgroundColor = Zone.getCellColor(7, 2);
  b[24].style.backgroundColor = Zone.getCellColor(7, 3);
  b[25].style.backgroundColor = Zone.getCellColor(7, 4);
  b[26].style.backgroundColor = Zone.getCellColor(7, 5);
  b[27].style.backgroundColor = Zone.getCellColor(7, 6);
  b[28].style.backgroundColor = Zone.getCellColor(7, 7);
  b[29].style.backgroundColor = Zone.getCellColor(7, 8);
  b[30].style.backgroundColor = Zone.getCellColor(6, 1);
  b[31].style.backgroundColor = Zone.getCellColor(6, 2);
  b[32].style.backgroundColor = Zone.getCellColor(6, 3);
  b[33].style.backgroundColor = Zone.getCellColor(6, 4);
  b[34].style.backgroundColor = Zone.getCellColor(6, 5);
  b[35].style.backgroundColor = Zone.getCellColor(6, 6);
  b[36].style.backgroundColor = Zone.getCellColor(6, 7);
  b[37].style.backgroundColor = Zone.getCellColor(6, 8);
  b[38].style.backgroundColor = Zone.getCellColor(5, 1);
  b[39].style.backgroundColor = Zone.getCellColor(5, 2);
  b[40].style.backgroundColor = Zone.getCellColor(5, 3);
  b[41].style.backgroundColor = Zone.getCellColor(5, 4);
  b[42].style.backgroundColor = Zone.getCellColor(5, 5);
  b[43].style.backgroundColor = Zone.getCellColor(5, 6);
  b[44].style.backgroundColor = Zone.getCellColor(5, 7);
  b[45].style.backgroundColor = Zone.getCellColor(5, 8);
  b[46].style.backgroundColor = Zone.getCellColor(4, 1);
  b[47].style.backgroundColor = Zone.getCellColor(4, 2);
  b[48].style.backgroundColor = Zone.getCellColor(4, 3);
  b[49].style.backgroundColor = Zone.getCellColor(4, 4);
  b[50].style.backgroundColor = Zone.getCellColor(4, 5);
  b[51].style.backgroundColor = Zone.getCellColor(4, 6);
  b[52].style.backgroundColor = Zone.getCellColor(4, 7);
  b[53].style.backgroundColor = Zone.getCellColor(4, 8);
  b[54].style.backgroundColor = Zone.getCellColor(3, 1);
  b[55].style.backgroundColor = Zone.getCellColor(3, 2);
  b[56].style.backgroundColor = Zone.getCellColor(3, 3);
  b[57].style.backgroundColor = Zone.getCellColor(3, 4);
  b[58].style.backgroundColor = Zone.getCellColor(3, 5);
  b[59].style.backgroundColor = Zone.getCellColor(3, 6);
  b[60].style.backgroundColor = Zone.getCellColor(3, 7);
  b[61].style.backgroundColor = Zone.getCellColor(3, 8);
  b[62].style.backgroundColor = Zone.getCellColor(2, 1);
  b[63].style.backgroundColor = Zone.getCellColor(2, 2);
  b[64].style.backgroundColor = Zone.getCellColor(2, 3);
  b[65].style.backgroundColor = Zone.getCellColor(2, 4);
  b[66].style.backgroundColor = Zone.getCellColor(2, 5);
  b[67].style.backgroundColor = Zone.getCellColor(2, 6);
  b[68].style.backgroundColor = Zone.getCellColor(2, 7);
  b[69].style.backgroundColor = Zone.getCellColor(2, 8);
  b[70].style.backgroundColor = Zone.getCellColor(1, 1);
  b[71].style.backgroundColor = Zone.getCellColor(1, 2);
  b[72].style.backgroundColor = Zone.getCellColor(1, 3);
  b[73].style.backgroundColor = Zone.getCellColor(1, 4);
  b[74].style.backgroundColor = Zone.getCellColor(1, 5);
  b[75].style.backgroundColor = Zone.getCellColor(1, 6);
  b[76].style.backgroundColor = Zone.getCellColor(1, 7);
  b[77].style.backgroundColor = Zone.getCellColor(1, 8);

}